ALTER TABLE incidents ADD COLUMN IF NOT EXISTS resolution_proofs JSONB DEFAULT '[]';
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS approvals JSONB DEFAULT '[]';
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS is_fully_approved BOOLEAN DEFAULT FALSE;
